### ISSUE TITLE
Content scheduling bug

### ISSUE THREAD

**Issue by KevRM** [CitizensBudgetCommission/cbcny-d8#198]

**Comment by peterserfozo** [comment]
I have started to debug this issue. It seems there is a timezone related bug (there are differences between timezone calculations of the date widget/saved publish dates). And the `scheduler` module is not up-to-date. Firstly, we should upgrade the module to the most recent version then I will fix this timezone issue if it won't be solved by upgrading the module.

**Comment by peterserfozo** [comment]
Updated the scheduler module and reviewed its configuration.
Please note that the scheduler runs depend on Cron (this is the server-side scheduler service). Currently, Cron runs every 3 hours. **I have set this value to 1 hour.** But it means if Cron runs at 10:00 AM and there is a scheduled content publishing at 10:30 AM, the scheduler will publish the content only at 11:00 AM because it depends on the Cron service and it runs per hour. So the worst-case scenario is that the scheduler will publish the node after an hour from the set publishing timestamp.
It is possible to start the scheduler manually if you do not want to wait for the next Cron run. In this case, you can visit https://cbcny.org/admin/config/content/scheduler/cron and click "Run Scheduler's lightweight Cron now"
